### ISSUE TITLE
Why not using a wiki instead ?

### ISSUE THREAD

**Issue by Offirmo** [yoshuawuyts/knowledge#42]
GitHub wikis are Git repos too, with a nicer interface.

**Comment by yoshuawuyts** [comment]
I'll probably turn this into a site at some point; finally got around to building a frontend framework that matches my opinions. The reason why it's a repo is because this repo is just another tab inside my tmux setup, and creating a git repo was the straight forward thing to do :sparkles:

<img width="1280" alt="screen shot 2016-08-29 at 22 28 09" src="https://cloud.githubusercontent.com/assets/2467194/18066273/fa10e68a-6e37-11e6-9588-43373472a8c8.png">

Hope this answers your question!

**Comment by Offirmo** [comment]
Ok interesting.
